### ISSUE TITLE
Is it possible to have nodes with outlines?

### ISSUE THREAD

**Issue by er4hn** [treilik/bubbleboxer#3]
Is it possible to have nodes with outlines in bubbleboxer? I'm hoping to create something similar to the soft-serve "git selector" + "git viewport" UI.

**Comment by treilik** [comment]
So what you can do is to embed a Boxer instance into a Model which draws a outline around it.
When you use this Model in a Leaf of a other Boxer instance, you have a outline around the contained nodes and leafs.
But at the moment its not directly possible.
