### ISSUE TITLE
Model with updates example

### ISSUE THREAD

**Issue by allyring** [treilik/bubbleboxer#8]
I think it would be helpful if there was an example that contained a model that updates, like a spinner, in the list of examples. It's one of the main features that's not clearly explained, so I think it would be beneficial.

**Comment by treilik** [comment]
thank you, i will look into it :)

**Comment by treilik** [comment]
Hope [this](https://github.com/treilik/bubbleboxer/commit/11bcb26858d15ba0b82efce24e9f13ff8be75381) helps!
The core take away is to manage the routing of messages in front of boxer.

If you have other requests or question please ask :)
Cheers!

**Comment by allyring** [comment]
Thanks so much :)
