### ISSUE TITLE
viewport leads to long line panic when resize

### ISSUE THREAD

**Issue by Jiaget** [treilik/bubbleboxer#9]
`VerticalStacked: true`

I make viewport  a children node, and resizing the terminal. and I got a `to long line` panic.

**Comment by treilik** [comment]
thanks! Did you handle the resizing of the viewport?
Or can you give me a bit more information, please?

**Comment by Jiaget** [comment]
I handle the resizing like that
```
		_ = m.tui.UpdateSize(msg)
		upperMsg := msg
		upperMsg.Height = upperMsg.Height / 3
		m.tui.ModelMap[upperModel].Update(upperMsg)
		lowerMsg := msg
		lowerMsg.Height = lowerMsg.Height * 2 / 3
		m.tui.ModelMap[lowerModel].Update(lowerMsg)
```

viewport is the `upperModel`.

And what's more should I do for the viewport?

**Comment by treilik** [comment]
Thanks, i will look into it.

**Comment by treilik** [comment]
would you mind adapting and testing against the develop branch?
since it contains breaking changes i keep it yet on develop.

**Comment by Jiaget** [comment]
It seems the panic message is printed on the screen rather than panic the program.
But the core problem still exists 

> The viewport's width is not changed while I am resizing the terminal.

After all. thanks for your job, it's easier for me to debugger it. 👏

**Comment by treilik** [comment]
I have look into it and found that viewport [does not handle windowsizemsgs](https://github.com/charmbracelet/bubbles/blob/master/viewport/viewport.go#L290) thus you have to set it your self.
Hope this helps! :)

**Comment by Jiaget** [comment]
I have handled the window size msg in viewport like that
```
		x, y := e.viewport.Style.GetFrameSize()
		e.viewport.Height = msg.Height - y
		e.viewport.Width = msg.Width - x
```
But it didn't work

And I observed the `lineWidth` and the `targetWidth` during resizing the terminal, the `lineWidth` sometimes is slightly bigger than `targetWidh`. I thought these two parameters' calculating speed is different, lineWidth's shrink speed may be slower than targetWidth . Finally, `lineWidth` will be smaller than `targetWidth`.

![image](https://user-images.githubusercontent.com/26248992/208635505-c94db732-63a4-4d64-ab72-722d3e257fbc.png)


I tried these codes, and in my case, it worked
```
			if lineWidth > targetWidth {
				lineWidth = targetWidth
			}
```
Will you accept this change?

**Comment by treilik** [comment]
would you please check against the latest commit on develop?

**Comment by Jiaget** [comment]
It seems you enriched the error message, and thanks to your work, I found both my upper model and the lower model, the width of them is always 1 character lower than the `targetWidth`

I changed all models' windowsSize handler in the box like that
```
		x, y := e.viewport.Style.GetFrameSize()
		e.viewport.Height = msg.Height - y - 1
		e.viewport.Width = msg.Width - x - 1
```

And the error message never appears.

**Comment by treilik** [comment]
OK, nice, thanks for checking and your welcome :)
